on:
  workflow_dispatch:
  schedule:
    - cron: '45 18 3,9,15,21,27 * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: li1ht2ay/it1h-z4@cron
        with:
          token: ${{ secrets.token }}
